name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - run: echo "TOKEN=${AUTH_TOKEN}"
        env:
          AUTH_TOKEN: ${{ secrets.PUSH_TOKEN }}
